### ISSUE TITLE
Search result of Collaboration

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#103]
1) After select the option “-Any-” from “All Industries” dropdown some  results are  displayed, but if I select the option “All” from “All Industries” drop down nothing is found.

2)In “All Industries” dropdown, so many options are repeated.

3) The options of all dropdowns should be display alphabetically  and “Others” options should be listed in end of the list.

All above issues are in Page Collaboration=> Search Collaboration(Link: http://makeitdeals.com/opportunity/search_collaboration) after loin as both partner, basicpartner and client

**Comment by salusn** [comment]
Issue fixed
