### ISSUE TITLE
Display search result

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#105]
I am bit confuse about the collaboration! The collaboration which I have created as Client(Collaboration=>Submit Collaborations) , these collaboration are listed in “Search Collaboration” page when I login as partner. But these Collaborations are not listed in search result when  I login as client.

**Comment by salusn** [comment]
If you are created a collaboration with login data:
 username : client
 password : 123

Then you can see that collaboration in "My Collaborations" tab.Not in the "Search Collaboration" list. This is same as Opportunity.
