### ISSUE TITLE
No Instruction in 2nd and 3rd drop down of Industry in submit  Collaboration

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#106]
When I create a Collaboration, there are some options in "Industry" . After select an option from first dropdown another  dropdown is coming but there is no name or any instruction in second dropdown also there is no instruction in 3rd dropdown.

**Comment by zivanta** [comment]
![colloaboration industry](https://cloud.githubusercontent.com/assets/18435821/21380694/03d8d918-c77d-11e6-81f5-75ac97efa26c.png)

**Comment by salusn** [comment]
Duplicate as #107
