### ISSUE TITLE
Search result of Collaboration #103

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#109]
1) After select the option “-Any-” from “All Industries” dropdown some results are displayed, but if I select the option “All” from “All Industries” drop down nothing is found.
2) In “All Industries” dropdown, so many options are repeated.

The options of all dropdowns should be display alphabetically and “Others” options should be listed in end of the list.
All above issues are in Page Collaboration=> Search Collaboration(Link: http://makeitdeals.com/opportunity/search_collaboration) after loin as both partner, basicpartner and client

These  issues are not fixed please recheck.

**Comment by salusn** [comment]
Please check now.
