### ISSUE TITLE
Workflow of Bidding system

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#110]
1) When a client posts any opportunity and invites a partner for a proposal,the partner is receiving the notification in the notification tab but there is no notification mail in the mail box nor does the website inform the partner about the notification by pop up. 

2) No option to the partner to submit proposal from the proposal notification detail page

3) What is a global tender and how will a client submit it?

4) There is no option to submit proposal on a global tender.

5) Once a proposal is shortlisted then it can't be reversed. How can a client cancel the shortlisted partner?

6) No notification was given to the partner when the proposal was shortlisted.

7) No notification is being given when a project is being awarded to a partner.

8) In "my opportunity" tab of client the name of the partner is not being shown to whom the project has been awarded. When we are clicking on the "Awarded" button no name of the partner to whom the project has been awarded has been shown.

**Comment by zivanta** [comment]
![awarded test point 8](https://cloud.githubusercontent.com/assets/18435821/21426298/2d757694-c874-11e6-9c5b-a6d496fd6588.jpg)

**Comment by salusn** [comment]
1.Email notification enabled when submitted a proposal.
2.Fixed.
5. Unshortlisting  /Cancel action is completed.
6.Enabled notification when a partner is shortlisted.
7.Enabled notification when a project is awarded.
8.Displayed the name of the partner to whom the project has been awarded.

All the above functionalities are updated in the "TEST SERVER".
