### ISSUE TITLE
Subscription Type

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#122]
I have login through a free account.
Then I have subscribed for premium/month.
But till its showing Subscription Type Free

**Comment by zivanta** [comment]
![subscription](https://cloud.githubusercontent.com/assets/18435821/21537589/ae68db0c-cdb9-11e6-836c-9bcf30401faf.png)

**Comment by salusn** [comment]
Issue fixed.

**Comment by zivanta** [comment]
I have Created a partner but did not subscribed. but Its showing 

Name
Subrata Zivanta
Membership Plan
Three Month Basic
Expire Date
2017-03-30

Then I have subscribed for premium plan but till its showing Membership Plan
Three Month Basic.
in admin panel its showing subrata.zivanta_1347 [ 0free, partner ]

**Comment by zivanta** [comment]
![subrata zivanta makeitdeals](https://cloud.githubusercontent.com/assets/18435821/21714508/584f3456-d425-11e6-8f6c-52be7d0f7d97.png)

Today found no Membership Plan or Expire detail information in live server...!!!

**Comment by salusn** [comment]
Issue fixed.Please check with new payment.
