### ISSUE TITLE
verified user

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#123]
After login through the username “basicpartner” which you have provided me. I have seen a verified check mark. How an user become a verified user?

**Comment by zivanta** [comment]
![verifieduser](https://cloud.githubusercontent.com/assets/18435821/21537612/fa228534-cdb9-11e6-93df-ea9f9e731eb9.png)

**Comment by salusn** [comment]
Except free subscription type, all other subscription types are confirmed as "verified" according to the document provided.

**Comment by zivanta** [comment]
Can you send me the full document?  We dont have this copy.

**Comment by zivanta** [comment]
I have created an account and subscribed but its not indicated as "verified" .
