### ISSUE TITLE
Subscription period

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#125]
You have subscribed one of the four option ie either per month or 3 months or 6 months or 12 months , then why should all options are enable during validity period. I am explaining.
 Suppose you have subscribed for three months. Then within 3 months its not possible to subscribe for per month. Then the option ”per month”  should be disable for 3moths.

**Comment by salusn** [comment]
Issue fixed.

**Comment by zivanta** [comment]
As i have seen after login as basic partner you have removed the button "Buy Now" from all plan. But If a basic partner want to subscribe for higher plan(I mean Standard and Premium plan) then what the do?
And another thing is After completion the subscription period what would be happen?
 I am explaining , suppose I am subscribed for 3 months ( any one of the 3  plans). my question is here after 3 months should I become a free member?

**Comment by sibizulu** [comment]
As I have seen after login as basic partner you have removed the button "Buy Now" from all plan. But If a basic partner want to subscribe for higher plan(I mean Standard and Premium plan) then what they do?
Here we do like this. If there is user with basic subscription, then we hide only basic level. Plase check once again 

And another thing is After completion the subscription period what would be happen?
It's shown in the profile page. When our subscription expire. It automatically unsubscribe from the plan and user is a free user then.

I am explaining , suppose I am subscribed for 3 months ( any one of the 3 plans). my question is here after 3 months should I become a free member?
yes
