### ISSUE TITLE
Page redirection

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#126]
After successful payment for subscription there is no option to return the main web site.

**Comment by salusn** [comment]
Please read on-screen instructions. 


![capture1](https://cloud.githubusercontent.com/assets/15374514/21537962/bc0f7a82-cdbd-11e6-9269-affadc2169e1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15374514/21537965/bfa1a1f2-cdbd-11e6-840b-3d19df2b14b7.PNG)

**Comment by zivanta** [comment]
If I click on your marked link, its goes to the  thank you page and after 10 sends its redirect to paypal home not website home page

**Comment by salusn** [comment]
Because of working with sandbox.

**Comment by zivanta** [comment]
Then how do I return to the website home page ie. http://makeitdeals.com/ after successful payment.

**Comment by salusn** [comment]
Now it is fixed.Please check.

**Comment by zivanta** [comment]
Yes... fixed but 
redirect should be to http://makeitdeals.com/subscriptions

**Comment by salusn** [comment]
Fixed...Please check.
