### ISSUE TITLE
Bidding Process

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#133]
User: client, basicpartner
Path: Login using basic partner > Notification > Select an invited Opportunity 

Issue: There is no button or link to submit proposal against that invited opportunity.

Detail:
1) Login into system using as “client”.
2) Submit an opportunity.
3) Search the opportunity.
4) Invite “basicpartner” to submit opportunity.
5) Login into system using “basicpartner”.
6) Go to Notification > select the invitation and go detail page.
7) There is no option to submit proposal on that opportunity.

**Comment by zivanta** [comment]
![unable to give proposal](https://cloud.githubusercontent.com/assets/18435821/21605479/86b94f50-d1cf-11e6-8013-f19bbe2b31b4.jpg)

**Comment by zivanta** [comment]
For reference...
![mitd_bidding_process](https://cloud.githubusercontent.com/assets/18435821/21605504/b1dd0320-d1cf-11e6-9b68-a647161dd4c6.png)

**Comment by salusn** [comment]
A basic partner can submit limited number of proposal for a month.That is why "No bid left" for basicpartner.You can create a new user with basic role and check.

**Comment by zivanta** [comment]
Good.... how can I change that limit as admin? And also the limit value was not written anywhere in partner's profile. Then how can a Partner know the limit value?

**Comment by salusn** [comment]
Admin management link for the subscription section is placed.
Displayed  the limit value for each subscription in the user profile.
Please check..
