### ISSUE TITLE
Bulletin board

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#135]
User: client / partner
Path: http://makeitdeals.com>login>oppurtunity>bulletin board
Issue: When no Client or user is selected it shows 'None' whereas it should be denoted as 'All'

**Comment by zivanta** [comment]
![screen 7](https://cloud.githubusercontent.com/assets/18435821/21605570/0870e8b4-d1d0-11e6-8e36-45fff2d3998e.png)

**Comment by salusn** [comment]
Issue fixed.

**Comment by zivanta** [comment]
Thanks for changes.... but at the same time all recorded should be visible when selected "All"

**Comment by salusn** [comment]
Only awarded opportunity will be displayed in the list.Please check
