### ISSUE TITLE
Improper Image tag

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#136]
Path: My Profile

An improper image tag is visible in Chrome Browser but in Firefox no image tag is showing.

**Comment by zivanta** [comment]
![makeitdeals_chrome](https://cloud.githubusercontent.com/assets/18435821/21889331/6c5fe0f8-d8ee-11e6-8430-b3e876ba7f54.png)
![makeitdeals_firefox](https://cloud.githubusercontent.com/assets/18435821/21889329/6b4ff86a-d8ee-11e6-993e-0e2baece26af.png)

**Comment by salusn** [comment]
Issue fixed.
