### ISSUE TITLE
Limitaion change of Bid value

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#137]
Path: My profile

Found no option to change the limitation of number of bid in admin account.

**Comment by zivanta** [comment]
![makeitdeals_change_limitation](https://cloud.githubusercontent.com/assets/18435821/21889584/b66d1534-d8ef-11e6-8df7-ed93d90cab02.png)

**Comment by salusn** [comment]
You can set limit value from the url:http://makeitdeals.com/madmin/config/subscription after login as  mitdadmin
