### ISSUE TITLE
Profile page Phone Number

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#15]
Phone number should take numbers, not any letters

**Comment by niksmac** [comment]
Duplicate to #16

**Comment by zivanta** [comment]
No 16 is for Mobile No and this for 10 digit validation. At least 10 digit have to submit

**Comment by zivanta** [comment]
Still it takes the letters. Check the Screenshot 
![phn](https://cloud.githubusercontent.com/assets/18435821/17771592/6f4b0532-6561-11e6-9744-35a0ff49d639.png)

**Comment by niksmac** [comment]
@zivanta Duplicate to #16, please follow up there.

**Comment by salusn** [comment]
duplicate #26
