### ISSUE TITLE
My Account to client tab error

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#35]
Click on My Account. Then click on My Opportunities tab. After that click on  read more... under opportunity section. Then details page and then if you click on CLIENT you get the attached image

**Comment by zivanta** [comment]
![21](https://cloud.githubusercontent.com/assets/18435821/17931219/ecf3c256-6a27-11e6-93df-b46cc9db463f.png)

**Comment by salusn** [comment]
This issue fixed
