### ISSUE TITLE
Client Section Change Password

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#40]
I click on Request new password. link under profile page. Then click on Email New Password. But still I can login through old password., whereas it should send a message like- your password has changed or forgot password link.

**Comment by niksmac** [comment]
Ideally, someone request password only when he forgot the password. 
And if we change the password on the request, it is not a logical behaviour. What if the password request is made my someone else using the email of a user?

**Comment by zivanta** [comment]
Yes your logic is right
