### ISSUE TITLE
Cost value mismatch with view section and input

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#65]
I put the Rate and Cost value as rate-ghhjk, cost- fghjkk, whereas after submit it shows a different Cost . Please check the  screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929217/47ca4d4e-a128-11e6-995d-7050e9835a72.png)

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929231/66346648-a128-11e6-9c4e-93e54511ede3.png)

**Comment by zivanta** [comment]
I have put cost as 345 but in view its not showing the value. Check the screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/20087733/28723f74-a5a1-11e6-95be-254e377fc918.png)

**Comment by salusn** [comment]
Issue fixed.
