### ISSUE TITLE
Objective of Collaboration of new functionality not matched

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#66]
Objective of Collaboration of new functionality not matched with old functionalities. In new collaboration submit form it shows a textarea, whereas in old function it shows a dropdown list.
Please check the attached screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929255/8550989e-a128-11e6-9596-d8c046972cf4.png)
![image](https://cloud.githubusercontent.com/assets/18435821/19929259/88991cb0-a128-11e6-9bf4-8d0c6dd9f74c.png)

**Comment by salusn** [comment]
Issue fixed.
