### ISSUE TITLE
Type of Collaboration  of new functionality not matched

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#67]
Type of Collaboration  of new functionality not matched with old functionalities. In new collaboration submit form it shows a text field, whereas in old function it shows a dropdown list. Please check the attached screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929285/a7851f84-a128-11e6-9644-f800aef91623.png)
![image](https://cloud.githubusercontent.com/assets/18435821/19929296/b1781f8c-a128-11e6-9514-b11f4581b757.png)

**Comment by salusn** [comment]
Issue fixed
