### ISSUE TITLE
Submit Collaboration another industry field add option

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#68]
In old Submit Collaboration form there is a option of add another industry field to that collaboration. But In new collaboration function there is no add another industry field option.
Please check the  screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929371/0a6927a8-a129-11e6-95b5-1a49d48f6f73.png)
![image](https://cloud.githubusercontent.com/assets/18435821/19929376/0fbb0d48-a129-11e6-9267-6be998ad70de.png)

**Comment by salusn** [comment]
Duplicate as #107
