### ISSUE TITLE
Add Another Item with the description field

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#69]
Onclick Add Another Item with the description field there should generate a document upload field.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929399/3135d80e-a129-11e6-8b84-e5957224e59a.png)

![image](https://cloud.githubusercontent.com/assets/18435821/19929403/35bb30ea-a129-11e6-8b67-b910db773148.png)

**Comment by salusn** [comment]
![addmore](https://cloud.githubusercontent.com/assets/15374514/20087316/5572063e-a59d-11e6-9751-6cf5cb864e75.PNG

First, upload a single file.Then we can see another file field to upload.

**Comment by zivanta** [comment]
Please check the test server again. In this I could not see the above kind function. After uploading a single file there is no file upload option is present.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/20087483/d8b4fb7c-a59e-11e6-8e10-854d603c143b.png)

**Comment by salusn** [comment]
Please check now.

**Comment by zivanta** [comment]
Now its working
