### ISSUE TITLE
Could not find the Hardware Technology input field

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#71]
Could not find the Hardware Technology input field whereas in View this field is present. But as per old site there should be Hardware Technology field in submit collaboration form. Please check the attached screenshot.

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929467/88b9b168-a129-11e6-9849-c680351e7165.png)

**Comment by salusn** [comment]
Issue fixed
