### ISSUE TITLE
Search Collaboration

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#73]
As per old site there should be Search Collaboration section with industry, segment, services etc dropdown at the top of search collaboration page like attached screen:

**Comment by zivanta** [comment]
![image](https://cloud.githubusercontent.com/assets/18435821/19929525/d005ab3a-a129-11e6-8062-ba35dc1690da.png)


![image](https://cloud.githubusercontent.com/assets/18435821/19929530/d3884d94-a129-11e6-81e3-b41a87a09642.png)

**Comment by salusn** [comment]
Issue fixed.
