### ISSUE TITLE
Button Padding not equal

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#75]
The button padding is not equal. An example: "Operating Systems", "Clouds".

**Comment by zivanta** [comment]
![screen2](https://cloud.githubusercontent.com/assets/18435821/21073033/ba39806c-befa-11e6-9976-047249bebae3.jpg)
![screen3](https://cloud.githubusercontent.com/assets/18435821/21073034/ba3d9602-befa-11e6-96cb-c9eb64e90a4f.jpg)

**Comment by niksmac** [comment]
Those are not buttons, just labels. There is no point in showing a fixed width label for few letters.
