### ISSUE TITLE
Error message in page

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#81]
An error message is shown in this link

http://makeitdeals.com/?q=bulletin-board/Opportunity_BulletinBoard

**Comment by zivanta** [comment]
![bulletin-board](https://cloud.githubusercontent.com/assets/18435821/21219861/806c8e3e-c2dc-11e6-93cd-f435e91a7f54.jpg)

**Comment by salusn** [comment]
Issue fixed
