### ISSUE TITLE
Page position

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#89]
Opportunities=>Submit Opportunity

After selecting “Complexity(Optional), Pre-Evaluation Criteria(Optional), Invite Selected Partners(Optional), Contact Manager(Pre-filled)” its bring me to top of the page

The page should be fix in corresponding section.

**Comment by zivanta** [comment]
![opportunity2](https://cloud.githubusercontent.com/assets/18435821/21221276/caa038c4-c2e2-11e6-8c30-ab5e15cc0c28.png)

**Comment by salusn** [comment]
No issue found when checked with chrome and mozilla..Is this issue browser specific?

**Comment by zivanta** [comment]
I have checked both chrome and mozilla, but right now nothing is happinening after clicking on those button. Please check.

**Comment by salusn** [comment]
Please check now.
