### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#90]
Opportunities=>Submit Opportunity

In View and preview section there are some links in Type of Project and Software Technology , After clicking on these links a page is opening without any content.

**Comment by zivanta** [comment]
![opportunity-link](https://cloud.githubusercontent.com/assets/18435821/21221343/0230c470-c2e3-11e6-9555-5c4ec5490412.png)

**Comment by salusn** [comment]
Issue fixed
