### ISSUE TITLE
wrong search

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#91]
Opportunities=>Submit Opportunity

I have created a opportunity test2 as a client, it has shown in search result in partner search opportunity.

I think the opportunity which I created as partner will show in search result when i login as a partner

**Comment by salusn** [comment]
Can you please explain?

**Comment by zivanta** [comment]
Hi Salusn,
  Thank you for feedback.I am explaining the issue.
 I have created an opportunity naming as test2 (right now it has been deleted) when I have  login as client(ie. Username : client)through the link http://makeitdeals.com/node/add/opportunity.
But this opportunity (test2)was display in the page  "Search Opportunity" when I login as partner(ie. Username; partner). The link was http://makeitdeals.com/?q=search/opportunities
But right now this page("Search Opportunity") has been deleted. 
Also as I have seen the page "Submit Opportunity" has been deleted (Login as partner).

**Comment by salusn** [comment]
You can login with username : basicpartner
                            password : 123

Only partners with basic,standard and premium memberships can see the above links.
