### ISSUE TITLE
Opportunity not shown

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#92]
Opportunities=>Submit Opportunity

When I create a opportunity test2 , I have selected the Software Technology “SAP”, But it is shown in searching result when I select technology “Java”.

test2 opportunity will not show when I select Java

**Comment by zivanta** [comment]
![opportunity3](https://cloud.githubusercontent.com/assets/18435821/21221474/822883de-c2e3-11e6-9a66-4916b577cd4e.png)

**Comment by salusn** [comment]
Issue fixed
