### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#93]
Opportunities=>Submit Opportunity

If I select The Technology “SAP” no result is found though i have creted a opportunity with Technology "SAP"

test2 opportunity will show when I select SAP

**Comment by zivanta** [comment]
![opportunity4](https://cloud.githubusercontent.com/assets/18435821/21221551/c99a58e6-c2e3-11e6-89ee-49afa2a133ba.png)

**Comment by salusn** [comment]
Issue fixed
