### ISSUE TITLE
No search result

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#94]
Opportunities=>Submit Opportunity

I have created a opportunity “My opportunity” But I did not find it in search result

Created opportunity should be display when i search

**Comment by salusn** [comment]
Not clear.Can you please explain?

**Comment by zivanta** [comment]
Hi Salusn,
  I am explaining the issue.
I have created an Opportunity naming as " My opportunity"(right now it has been deleted )after login as partner(ie. Username: partner) through the link http://makeitdeals.com/?q=node/add/opportunity(right now this link is not exist).
But when I search the opportunity in the page Opportunities=>Search Opportunity (link http://makeitdeals.com/?q=search/opportunities . right now this link is also removed), the opportunity which I have created(ie. My opportunity) is not listed in search result.

**Comment by niksmac** [comment]
I belive that is a sensible way to do it. There is no need of appearing my opportunity in search result right? 

Please confirm.
