### ISSUE TITLE
Unknown sysmbol

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#95]
My Account=> My Opportunity

There is a bar with glob symbol and a word 556ff.

**Comment by zivanta** [comment]
![opportunity](https://cloud.githubusercontent.com/assets/18435821/21221762/af0c74e0-c2e4-11e6-8ba0-3070332bbb32.png)

**Comment by salusn** [comment]
The icon is used to represent the website of the client who posted the opportunity.
