### ISSUE TITLE
Workflow of Bidding system

### ISSUE THREAD

**Issue by zivanta** [niksmac/mitd#97]
We are little bit confused about workflow of bidding system.

To clear the confusion we draw a workflow diagram. Please confirm it.

**Comment by zivanta** [comment]
![mitd_bidding_process](https://cloud.githubusercontent.com/assets/18435821/21286201/883a4f28-c473-11e6-917c-6265637ac75f.png)

**Comment by salusn** [comment]
We implemented the same functionality.
